// Bundle-size guard. Fails the build when a chunk grows past its ceiling.
//
//   node scripts/check-size.mjs           credential-less build (local default)
//   node scripts/check-size.mjs --prod    build made WITH VITE_SUPABASE_* set
//
// 🔴 WHY TWO BUDGET SETS. Without `VITE_SUPABASE_URL`/`ANON_KEY`, rollup drops
// every sync path and the whole `@supabase/*` client with it — StaffApp is
// 340 KB credential-less and 581 KB prod-shaped. Those are BOTH real builds and
// comparing one against the other's numbers is meaningless, which is a mistake
// this repo has already made in prose. CI builds prod-shaped (see deploy.yml),
// so CI runs `--prod`; a bare local `npm run build` is the local set.
//
// The mode is ASSERTED, not assumed: `GoTrueClient` is an @supabase/auth-js
// internal that only survives when the client is actually bundled, so asking
// for the wrong set fails loudly instead of passing against numbers that do not
// describe the build in front of it.
//
// These are CEILINGS to catch unintended drift, not targets — roughly 4% over
// what the tree measured when they were set. If a deliberate feature pushes one
// over, raise it IN THE SAME COMMIT and say what bought the bytes. Silently
// raising a budget is the same as not having one.
//
// 📏 The member path is the number that matters commercially: it is what someone
// who is not a customer downloads to look at one class. It was 206.69 KB at
// session 19 and is 213.50 KB now — that drift is exactly what this catches.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const ASSETS = path.join(root, "dist", "assets");
const prod = process.argv.includes("--prod");
// 1000, not 1024 — vite reports kB and every size recorded in this repo's docs
// is vite's number. A guard that quotes KiB would disagree with the handoff by
// 2.4% and someone would eventually "fix" the wrong one.
const KB = 1000;

// Chunk name → ceiling in KB, per build shape. Measured 2026-08-03.
// ⚠️ An UNLISTED chunk is counted in the file total and has no ceiling at all, so
// a new lazy chunk that is not added here can grow without ever failing this
// guard. RetentionScreen (N2) measured 11.09 KB credential-less when it landed;
// its ceiling is 14 rather than the usual +4% because the PROD-shaped number
// cannot be measured locally — no credentials — and CI is the run that judges it.
// Its contents are app code plus lib/cohorts.js, with nothing supabase-shaped of
// its own, so the two build shapes should agree closely.
//
// BrandStudioScreen (session 28 §2.2) measured 26.50 KB credential-less; 28 is
// the usual +4%. Its PROD ceiling is 30 rather than 28 for a reason worth
// naming: this screen imports `supabase` directly (it writes brand_profiles), so
// a prod build COULD in principle pull client code in here rather than leaving
// it in the shared chunk. It should not — App.jsx and store.js import the same
// client, so rollup hoists it — and if CI ever reports this chunk over, that
// hoisting is the thing to look at, not the screen.
//
// LibraryBrowserModal 19.15 KB and ProfileModal 13.71 KB, same session, same
// +4%. Both are app code with no supabase surface of their own, so the two build
// shapes should agree and the prod ceilings are one KB looser only to absorb
// minifier drift between shapes.
//
// ─── §2.6 · WHAT IS ACTUALLY IN index.js — measured, session 29 ──────────────
//
// The queue called this "the thing that will block the session after next" and
// asked for the top ten contributors. Nobody had looked. Attributed by decoding
// the sourcemap's VLQ mappings — every generated byte charged to the module it
// came from, not estimated:
//
//   react-dom/react-dom-client.production.js   172.40 KB   85.7%
//   react/react.production.js                    7.44 KB    3.7%
//   src/lib/colors.js                            7.26 KB    3.6%
//   scheduler/scheduler.production.js            3.53 KB    1.8%
//   react-dom/react-dom.production.js            3.25 KB    1.6%
//   src/ui/ErrorBoundary.jsx                     2.54 KB    1.3%
//   src/main.jsx                                 1.24 KB    0.6%
//   react/react-jsx-runtime.production.js        0.37 KB
//   react-dom/index.js, client.js, react/index.js, jsx-runtime, scheduler/index
//   src/lib/classToken.js                        0.14 KB
//
//   dependencies 187.84 KB (93%) · OUR OWN CODE 11.19 KB (5.6%)
//
// 🔴 SO THE ANSWER IS THAT IT IS ALL LOAD-BEARING, AND THE PREMISE NEEDS
// CORRECTING: this chunk is not tight because app code crept into it. It is 93%
// React, and the 215 KB budget was set close to React's floor. There are 11 KB of
// our own code in it, of which ErrorBoundary must be eager by definition,
// main.jsx IS the entry, and classToken parses a member link before anything
// loads. Moving app code around cannot solve this, because there is almost no app
// code to move.
//
// The ONE lever was `colors.js`, and session 29 pulled it: 2.84 KB of owner-only
// generator (`extractPalette`, `generateThemes`, `generateSkinFromPalette`,
// `nudgeContrast`, `DEFAULT_PROGRAMS`) is now `brandGenerator.js`, a shared lazy
// chunk. index.js 206.02 → 203.06 KB, headroom 4.2% → 5.6%. That is the whole of
// what code movement can buy here.
//
// ⚠️ WHY IT WAS EAGER, because it is a trap worth naming: `main.jsx` imports ONE
// function from `colors.js` — `bootColours`, for the pre-hydration splash — and
// rollup places whole MODULES, so that single edge put the entire file, generator
// included, in the chunk a member downloads to look at one class.
// `BrandStudioScreen.jsx`'s header claimed the opposite in writing for a whole
// session. Any future eager import from a module is an import of all of it.
//
// What is left if this ever needs to move again is not a refactor: it is React
// itself (a preact/compat swap is infra and Dylan's), or raising the ceiling and
// saying so.

// 🔴 RetentionScreen 14 → 18 (session 28 §2.6). What bought the bytes: the
// class-type return-rate panel — `lib/classTypeRetention.js` plus its markup,
// which is the "which of your classes keeps members" ranking. Measured 17.02 KB
// credential-less, up from 12.04. It lands here rather than in a chunk of its
// own because it is the SAME route (`analytics`) and the same screen: two lazy
// chunks for one screen would mean two fetches to render it, which is worse than
// four KB.
// 🔴 BrandStudioScreen 28 → 30 credential-less, 30 → 32 prod (session 29 §2.1).
// What bought the bytes: the re-read offer for gyms whose stored palette came
// from the generator's fallback rather than their logo — the detector's two
// frozen token sets and comparison in `skins.js`, plus the banner's markup and
// copy. Measured 28.20 KB, up from 26.55.
//
// ⚠️ THE BYTES DID NOT ALL LAND WHERE THE FEATURE DID, and it is worth naming
// because guessing gets it wrong. Measured across the three chunks:
//
//   BrandStudioScreen.js  26.55 → 28.20  the banner's markup and copy
//   StaffApp.js          292.32 → 292.89  the detector itself
//   index.js             204.72 → 204.72  unchanged
//
// The detector lives in `lib/skins.js`, which App.jsx imports — so it is placed
// in `StaffApp.js`, the chunk both readers share, not in the lazy screen that
// asked for it. Nothing eager reaches `skins.js`, which is why the entry chunk
// is untouched. A future caller in `main.jsx` or its imports WOULD move it into
// `index.js`, the chunk with the least headroom in the build.
// BrandStudioScreen 30 → 32 credential-less, 32 → 34 prod (session 29 §2.2).
// What bought the bytes: the AA audit widened from five opaque token pairs to
// fourteen, including the composited chip, danger and warning plates — the rows
// `e2e/brandTokens.spec.js` was already failing palettes on while the panel
// called them accessible. Measured 29.98 KB, which is 0.1% of headroom and the
// reason this line moves rather than shipping on the edge of the ceiling.
//
// ⚠️ `index.js` 204.72 → 205.97, and this one IS the entry chunk. The shared
// compositing (`parseCssColor`, `compositeOver`, `luminanceRgb`, `contrastRgb`,
// `mixSrgb`) lives in `colors.js`, which `main.jsx` already pulls in eagerly for
// `bootColours` — so anything added to that module is added to what a member
// downloads to look at one class. 1.25 KB for one implementation instead of two
// is worth it; the module being eager AT ALL is §2.6's problem, not this one's.
// PTScreens.js (F1's 1:1 lens + the PAR-Q gate) is BOTH screens in one chunk —
// App.jsx lazy-loads the barrel twice on purpose, because two dynamic imports of
// two files would emit a third, generated-name chunk for the shared libs, and
// the ⚠️ above is exactly about that chunk having no ceiling. Its ceiling is set
// the same way RetentionScreen's was: the credential-less number measured when
// it landed, plus room, with the prod figure a little wider because it cannot be
// measured locally and CI is the run that judges it. Nothing supabase-shaped is
// in it, so the two shapes should agree closely. Measured 31.52 KB
// credential-less when it landed: two full screens, the seven PAR-Q question
// texts, and lib/parq.js + lib/ptClients.js, none of which the eager bundle
// pays for.
// ─── MERGE NOTE (integrating the S29–S33 stack onto main) ───────────────────
// Both sides rewrote BUDGETS and neither superseded the other, so this is the
// UNION, not a pick. From main: PTScreens (F1's 1:1 lens). From the stack:
// BrandStudioScreen, LibraryBrowserModal, ProfileModal, brandGenerator, and
// RetentionScreen 14 -> 18 (the class-type return-rate panel bought those
// bytes; main's 14 predates it). Every other ceiling is identical on both sides.
const BUDGETS = prod
  ? { "index.js": 215, "StaffApp.js": 610, "PersonasScreen.js": 100, "RetentionScreen.js": 18, "PTScreens.js": 36, "BrandStudioScreen.js": 34, "LibraryBrowserModal.js": 21, "ProfileModal.js": 15, "ClassSummary.js": 8, "summaryApi.js": 5, "brandGenerator.js": 4 }
  : { "index.js": 215, "StaffApp.js": 360, "PersonasScreen.js": 100, "RetentionScreen.js": 18, "PTScreens.js": 34, "BrandStudioScreen.js": 32, "LibraryBrowserModal.js": 20, "ProfileModal.js": 15, "ClassSummary.js": 8, "summaryApi.js": 3, "brandGenerator.js": 4 };
// What a browser actually downloads, which is the claim worth defending.
const PATHS = prod
  ? { member: 225, staff: 825 }
  : { member: 222, staff: 575 };

if (!fs.existsSync(ASSETS)) { console.error(`no dist/assets — run \`npm run build\` first`); process.exit(2); }
const files = fs.readdirSync(ASSETS).filter(f => /\.(js|css)$/.test(f));
// A guard that measured nothing looks exactly like a guard that passed.
if (!files.length) { console.error("dist/assets holds no js/css — nothing was measured"); process.exit(2); }

const sizeOf = f => fs.statSync(path.join(ASSETS, f)).size / KB;
// Vite hashes filenames; the logical chunk is everything before the last dash.
const logical = f => f.replace(/-[A-Za-z0-9_-]{8,}(\.\w+)$/, "$1");
const byName = new Map(files.map(f => [logical(f), sizeOf(f)]));

// ── Assert the build in front of us is the one we were told to judge ─────────
const hasClient = files.some(f => /\.js$/.test(f)
  && fs.readFileSync(path.join(ASSETS, f), "utf8").includes("GoTrueClient"));
if (prod && !hasClient) {
  console.error("--prod was given but no @supabase client is bundled — this is a CREDENTIAL-LESS build.\n"
    + "Build with VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY set, or drop --prod.");
  process.exit(2);
}
if (!prod && hasClient) {
  console.error("this is a PROD-SHAPED build but --prod was not given — the local budgets do not describe it.\n"
    + "Re-run with --prod.");
  process.exit(2);
}

const get = n => byName.get(n) ?? 0;
const memberPath = get("index.js") + get("index.css") + get("ClassSummary.js") + get("summaryApi.js");
const staffPath = get("index.js") + get("index.css") + get("StaffApp.js") + get("StaffApp.css");

let failed = 0;
const line = (label, kb, budget) => {
  const over = kb > budget;
  if (over) failed++;
  const pct = budget ? ((budget - kb) / budget * 100).toFixed(1) : "0";
  console.log(`${over ? "OVER " : "ok   "} ${label.padEnd(20)} ${kb.toFixed(2).padStart(8)} KB`
    + `  budget ${String(budget).padStart(4)} KB`
    + (over ? `  — ${(kb - budget).toFixed(2)} KB OVER` : `  (${pct}% headroom)`));
};

console.log(`\nbundle size — ${prod ? "PROD-SHAPED" : "credential-less"} build\n`);
for (const [name, budget] of Object.entries(BUDGETS)) {
  if (!byName.has(name)) { console.error(`MISSING ${name} — expected chunk not emitted`); failed++; continue; }
  line(name, get(name), budget);
}
console.log("");
line("member path", memberPath, PATHS.member);
line("staff path", staffPath, PATHS.staff);
console.log(`\n(member path = index.js + index.css + ClassSummary.js + summaryApi.js;`
  + ` staff = index + StaffApp; PersonasScreen ${get("PersonasScreen.js").toFixed(2)} KB,`
  + ` RetentionScreen ${get("RetentionScreen.js").toFixed(2)} KB`
  + ` and PTScreens ${get("PTScreens.js").toFixed(2)} KB load lazily)`);

console.log(`\nmeasured ${files.length} files · ${failed} over budget`);
process.exit(failed ? 1 : 0);
